name: Publish NexaWrap.SQS.NET

on:
  push:
    tags:
      - "v*.*.*"  # Runs when a versioned Git tag is pushed (git tag v1.0.0, git push origin v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Pack NexaWrap.SQS.NET
        run: dotnet pack src/NexaWrap.SQS.NET/NexaWrap.SQS.NET.csproj --configuration Release --output ./packages

      - name: Publish NexaWrap.SQS.NET to NuGet
        run: dotnet nuget push ./packages/NexaWrap.SQS.NET.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate